### ISSUE TITLE
Improve usability by adding a prefactor for HILL-formula

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-hill-spreading#2]
I came across a usecase where it was beneficial to have a prefactor to scale the HILL-formula.

I would call it an improvment if this access-point where added to the plug-in.
[hill_spreading.py.txt](https://github.com/user-attachments/files/16884866/hill_spreading.py.txt)

**Comment by ChRen95** [comment]
In the original publication by Hill, the Author referred to the value of 0.5 as a arbitrary pre factor. 
With the new update I made this value accessible, you implementation would mean a general correction factor which should be implemented in the core. Maybe this implementation already works out

**Comment by GRPlan** [comment]
The implemented way is sufficient for my application. Thanks a lot.
